development:
  url: <%= ENV['DATABASE_URL'] %>
  # mysql2://codeboxx:Codeboxx1!@codeboxx.cq6zrczewpu2.us-east-1.rds.amazonaws.com:3306/csl
  
dwh_development:
  url: <%= ENV['DWH_URL'] %>
  # postgres://codeboxx:Codeboxx1!@codeboxx-postgresql.cq6zrczewpu2.us-east-1.rds.amazonaws.com:5432/MaximeAuger_psql
